site_name: My IT Journal
repo_url: "https://github.com/rosariolm/myjournal"
repo_name: "rosariolm/myjournal"
edit_uri: "edit/main/docs"

theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - tabs
    - instant
    - content.tabs.link
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - mavigation.top
  icon:
    logo: material/library
    repo: fontawesome/brands/gitlab
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: octicons/checklist-16
      info: octicons/info-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  name: material
  primary: indigo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk

nav:
  - Home: index.md
  - Tagesberichte: tberichte.md
  - Archiv:
      - "2022":
          - "Juni 2022": archiv/Juni2022.md
          - "Mai 2022": archiv/Mai2022.md
          - "April 2022": archiv/April2022.md
          - "März 2022": archiv/März2022.md
          - "Februar 2022": archiv/Februar2022.md
          - "Januar 2022": archiv/Januar2022.md
      - "2021":
          - "Dezember 2021": archiv/Dezember2021.md
          - "November 2021": archiv/November2021.md
          - "Oktober 2021": archiv/Oktober2021.md
          - "September 2021": archiv/September2021.md
  - Wochenberichte:
      - "BI":
          - "Multiboot-USB-Stick": wberichte/w18_YUMI.md
          - "Firmware Update": wberichte/w12_firmware.md
          - "Autopilot Script Anpassung": wberichte/w8_AutoPilotScript.md
          - "Gerät bei Autopilot hinzufügen": wberichte/w7_AutoPilot.md
          - "Bootcamp": wberichte/w6_Bootcamp.md
          - "PIN Deaktivierung in Intune": wberichte/w5_PIN.md
      - "INF":
          - "Netzwerkadresse berechnen": wberichte/w4_NetzAdrBerechnen.md
          - "Link Aggregation": wberichte/w50_LinkAggregation.md
          - "VLAN hinzufügen": wberichte/w48_VlanHinzufuegen.md
          - "Switch Taggen und untaggen": wberichte/w47_SwitchTaganduntag.md
          - "Tag im Ethernet Frame": wberichte/w45_TagImEthernetFrame.md
      - "HPC":
          - "Gelerntes": wberichte/gelerntes.md
          - "Vagrant Befehle": wberichte/w40_vagrant.md
          - "git Q & A": wberichte/w37_gitQandA.md
          - "Workflow": wberichte/w36_workflow.md
          - "git Befehlsreferenz": wberichte/w34_gitcheat.md
          - "MkDocs installieren": wberichte/w33_mkdocs.md
  - Arbeitshefter:
      - "Bi":
          - "Inhaltsverzeichnis": aberichte/Bi/bi_verzeichnis.md
      - "INF":
          - "Inhaltsverzeichnis": aberichte/inf/verzeichnis.md
          - "ISO/OSI Modell": aberichte/inf/IsoOsi.md
          - "Layer 1": aberichte/inf/layer1.md
          - "Layer 2": aberichte/inf/layer2.md
          - "Layer 3": aberichte/inf/layer3.md
          - "Praktische Arbeiten und Erfahrung": aberichte/inf/4.md

markdown_extensions:
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.critic
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins:
  - search
  - git-revision-date-localized:

copyright: Copyright &copy; 2022 Laura Marie Rosario
